### ISSUE TITLE
please document how to uninstall / completely disable lolcommits

### ISSUE THREAD

**Issue by jononomo** [mroth/lolcommits#281]
I tried uninstall the gem and also deleting the .lolcommits folder from my home directory.  But now it just throws an error every time I do a git commit.

**Comment by matthutchinson** [comment]
You'll need to remove the git post commit hook  Normally if you already have the gem installed, in the git repository you use lolcommits, you'd simply type; 

`lolcommits --disable`

(this is documented in `lolcommits --help` output, our [README](https://github.com/mroth/lolcommits#other-commands) and our gem's [homepage](https://lolcommits.github.io))

If you'd like I can add it to our wiki too as an FAQ. 

If you don't have the gem installed to `--disable` it, you'll need to manually remove the post-commit hook that was created by lolcommits. 

To do this, edit the file at `/path/to/your/repo/.git/hooks/post-commit` removing the lines for the lolcommits hook (or delete this file entirely if you have no other hooks in use).

We could change the post-commit hook to fail silently if it can't find the lolcommits executable, but we don't really want to do this, since often that error is a sign somethings wrong with the user's PATH or environment.

**Comment by matthutchinson** [comment]
Updated our wiki with this information [here](https://github.com/mroth/lolcommits/wiki/FAQ#how-do-i-uninstall-or-disable-lolcommits)
