### ISSUE TITLE
Drop Ruby 1.8?

### ISSUE THREAD

**Issue by Ruxton** [mroth/lolcommits#310]
Can we drop 1.8 support? It's EOL. Anyone using 1.8 is on old un-supported OS versions or using an un-supported ruby with security holes.

**Comment by matthutchinson** [comment]
So we've been wanting to do this for a looonnggg time.  Unfortunately I believe there are still some linux distributions which ship with 1.8 as the system Ruby (I have a long standing to-do to verify what dist's these are).

Dropping support for 1.8 would help us upgrade a bunch of gems, and it seems to make sense since its EOL - just need to be sure we're not cutting off a largish user base - a lot of non-ruby devs use lolcommits on unix systems, and no nothing of rbenv or RVM.  Windows one-click installer is now happily working with 2.0+ so there is no dependency there (since M$ doesn't ship with windows, and our guide explains what to do)

@mroth - is this still your assumption too?  Another option would be to tag/pin an old version of the gem for 1.8 to use going forward... and we'd drop the support on the main branch and future versions...  With a caveat in the README explaining to 1.8 users what to do...  What do you think?

**Comment by matthutchinson** [comment]
@Ruxton random unrelated question ... is it OK if I use one of your lolcommit images on our [repo](https://github.com/mroth/lolcommits#sample-images) README sample images (and [here too](https://lolcommits.github.io/)).. I'd like to show off the new style commits a bit more, and have a couple of different people in the snaps, (instead of just me 😄) ... If not no worries 👍

**Comment by Ruxton** [comment]
@matthutchinson no problemo, I have lots if you want some more :)

**Comment by mroth** [comment]
@matthutchinson I can potentially see dropping 1.8 support, but it's possibly a major-ish semver version bump in order to let people easily pin.

**Comment by matthutchinson** [comment]
I'll prep a PR to see what we can upgrade by dropping 1.8 support.

Iif it has enough advantages, I say we do it, then bump from `0.6.7` to `0.7.0` and tag this as the last supported Ruby 1.8 release, --and issue a new `0.8` for Ruby 1.9+..

I don't think this warrants a 1.0 release, since effectively we're just deprecating Ruby 1.8 support

What do you think?

**Comment by matthutchinson** [comment]
OK, I worked on this for a while today, and managed to get mostly all gems upgraded to their latest versions apart from the following;

```
s.add_runtime_dependency('rest-client', '=1.8')   # yam gem requires uses this older version           
s.add_runtime_dependency('mime-types', '=2.99')   # ~> 3.0+ requires Ruby >= 2.0                       
s.add_runtime_dependency('json', '~> 1.8.3')      # ~> 2.0+ requires Ruby >= 2.0 (lolsrv)       
       
s.add_development_dependency('tins', '=1.6.0')    # ~> 1.7.0+ requires Ruby >= 2.0                     
s.add_development_dependency('rake', '~> 10.5.0') # ~> 11+ introduces lots of warnings from other deps 
s.add_development_dependency('aruba', '~> 0.6.2') # upgrading requires a lot of test code changes      
```

The main benefits are;

* we're on the latest versions of many more gems, including cucumber, rubocop and twitter
* we're on the latest MiniMagick, meaning snaps no longer text quoted on modern rubies
* future upgrade work is easier (including extracting plugins out)
* less legacy rubies to maintain going forward 👍 
* test runs are a little faster 🐎 

[Here](https://github.com/mroth/lolcommits/compare/master...drop-ruby-18-support-upgrade-gems?diff=unified&name=drop-ruby-18-support-upgrade-gems&pull_request) are the code changes:  https://github.com/mroth/lolcommits/compare/master...drop-ruby-18-support-upgrade-gems?diff=unified&name=drop-ruby-18-support-upgrade-gems&pull_request

and build is green on [Travis CI](https://travis-ci.org/mroth/lolcommits/builds/142517485)

I haven't created a PR yet, since we'd want to release a `0.7.0` first, and explain we're dropping Ruby1.8.7 support from 0.8 onward in the README/wiki etc.

 ❓ @mroth - let me know if you are OK with me to proceed with this plan ❓ 

Upgrading aruba requires significant effort, since they've changed and deprecated a lot since `0.6.2`. (could be done in the future)...

You can see from the gemspec that if we dropped Ruby 1.9 support and went right to 2.0+ we could update 2 more runtime gems and 1 test gem - Ruby1.9 (and even 2.0.0) are 'end of life' now - but lets leave that for the future too..

**Comment by mroth** [comment]
Most excellent! :+1:

**Comment by matthutchinson** [comment]
Great, I'll get these new releases out asap 👍

**Comment by matthutchinson** [comment]
OK, with [this PR](https://github.com/mroth/lolcommits/pull/313) `0.7.0` and `0.8.0` releases are now out (both tested on OSX, Ubuntu and Windows (via VM)) 

The [README](https://github.com/mroth/lolcommits/blob/master/README.md) now includes a _Requirements_ section up front, and the _Installation_ section, mentions that for older Rubies, `0.7.0` is available.

And the [CHANGELOG](https://github.com/mroth/lolcommits/blob/master/CHANGELOG.md) explains things further.

I'll mark this issue closed 👍
